console.log(5)
console.log(999)
console.log(99.4)
console.log(9n)
console.log(9999999999999999999999999)
console.log("edson")
console.log("8")
console.log("edson" [0])
console.log("edson".length)
console.log(true)
console.log(false)
console.log(null)
console.log(undefined)
console.log(typeof console)
console.log(typeof 5)
console.log(typeof "edson")
console.log(typeof console.log)