console.log(1 + 1)
console.log(7 - 4)
console.log(3 * 8)
console.log(6 / 7)
console.log(10 % 3)
console.log(1 + 1 * 9)
console.log((1 + 1) * 9)
let a = 5 
console.log(a)
console.log(a + 3)
console.log(a = a + 3)
console.log(a += 4)
console.log(a -= 4)
console.log(a *= 4)
console.log(a /= 4)
console.log(a %= 4)
console.error("ERRO")
console.log("edson" + " souza")